### ISSUE TITLE
Tracking 1.0

### ISSUE THREAD

**Issue by retrixe** [retrixe/coupe-video#1]
- [x] #2
- [x] `Set Timestamp to Current` buttons
- [ ] Service worker and manifest.json
- [ ] Fix Chrome Android support
- [x] Improved error handling
- [ ] Handle vertical videos
- [x] Browser support info
- [x] Select file button
- [x] Input validation
- [x] README.md

**Comment by retrixe** [comment]
Postponing #2 to a future version release.
